### ISSUE TITLE
dock栏插件区域偏灰色，与思源自带的标签等区域颜色不同

### ISSUE THREAD

**Issue by QMike0** [chenshinshi/chrome-a4#2]
如题，对于插件在docker栏的显示，背景都是灰色：（例如插件“书签+”）
![image](https://github.com/user-attachments/assets/87407e1a-2f5a-41e3-b815-c3a818029c4d)
而对于思源自带的docker栏区域，例如文档树、标签、书签等，都是白色
![image](https://github.com/user-attachments/assets/16a72b43-ac3b-4c31-b861-eacf9bd55f58)

无论插件还是思源默认docker栏区域，能否统一修改为白色背景，感觉视觉上更舒服一些

**Comment by chenshinshi** [comment]
收到！感谢反馈！！！
